version: '2.2.0.{build}'
only_commits:
  files:
    - src\simplexcel\*
    - appveyor.yml
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
configuration:
- Release
image:
- Visual Studio 2017
platform: Any CPU
init:
- ps: $Env:LABEL = $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\
install:
  - cmd: dotnet --version
  - cmd: rd /S /Q src\Simplexcel.MvcTestApp
  - cmd: rd /S /Q src\Simplexcel.TestApp
before_build:
  - cmd: dotnet sln remove src\Simplexcel.MvcTestApp\Simplexcel.MvcTestApp.csproj src\Simplexcel.sln
  - cmd: dotnet sln remove src\Simplexcel.TestApp\Simplexcel.TestApp.csproj src\Simplexcel.sln
build_script:
- appveyor-retry dotnet restore -v Minimal src
- dotnet test src
- dotnet pack src --configuration %CONFIGURATION% -o ..\..\nuget
artifacts:
- path: nuget\*.nupkg