name: CI Build


on:
  pull_request:
  push:
    branches:
    - master
    paths:
    - 'src/simplexcel/*'
    - '.github/workflows/*'
    - 'scripts/*'
    - '!/docs/*' # Don't run workflow when files are only in the /docs directory

jobs:
  build:
    name: Windows
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    # To avoid vendor lock-in, this is mostly driven by a build script
    - name: Run build script
      shell: pwsh
      run: |
        $Env:GIT_BRANCH=$Env:GITHUB_REF
        $Env:GIT_BRANCH = $Env:GIT_BRANCH -ireplace "refs/heads/", ""
        $Env:GIT_BRANCH = $Env:GIT_BRANCH -ireplace "origin/", ""
        cd scripts
        ./build.ps1
        Get-ChildItem Env: | Where-Object {$_.Name -Match "^MH_"}
  publish-gpr:
    name: Publish to GitHub Package Repository
    runs-on: windows-latest
    needs: [build]
    steps:
    - name: Testing 123
      shell: pwsh
      run: |
        Get-ChildItem Env: | Where-Object {$_.Name -Match "^MH_"}
