name: CI Build


on:
  pull_request:
  push:
    branches:
    - master
    paths:
    - 'src/simplexcel/*'
    - '.github/workflows/*'
    - 'scripts/*'
    - '!/docs/*' # Don't run workflow when files are only in the /docs directory

jobs:
  build:
    name: Windows
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    # To avoid vendor lock-in, this is mostly driven by a build script
    - name: Run build script
      shell: pwsh
      run: |
        $Env:GIT_BRANCH=$Env:GITHUB_REF
        $Env:GIT_BRANCH = $Env:GIT_BRANCH -ireplace "refs/heads/", ""
        $Env:GIT_BRANCH = $Env:GIT_BRANCH -ireplace "origin/", ""
        cd scripts
        ./build.ps1
        Get-ChildItem Env: | Where-Object {$_.Name -Match "^MH_"}
        
        # Publish Packages if successful
        $nupkgPath = "$Env:MH_BUILD_OUTPUT/simplexcel.$Env:MH_BUILD_VERSION_PACKAGE.nupkg"
        If ($Env:MH_IS_PROD_BUILD -eq "True") {
          # TODO: Publish to Nuget
        } else {
          # Publish to GitHub Package Repository
          Write-Host "Publishing $nupkgPath to GitHub Package Repository"          
          dotnet nuget push "$nupkgPath" -k "${{ secrets.GITHUB_TOKEN }}" -s "https://nuget.pkg.github.com/mstum/index.json"
        }
